### ISSUE TITLE
Update RubyGems version

### ISSUE THREAD

**Issue by pacMakaveli** [hschne/rails-mini-profiler#21]
Found a bug? Please fill out the sections below! 👍

### Issue Summary

Complains about speedrun index.html with the RubyGem version. Seems to work fine by bundling the github source.

### Steps to Reproduce

1. Follow the installation instructions from the git and try to view a flamegraph

### Technical details

Rails 6.1.4
➜  games.directory git:(develop) ✗ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
➜  games.directory git:(develop) ✗

**Comment by hschne** [comment]
Thanks for contributing so much! :heart_eyes: 

This issue should be fixed with the latest release. The problem was, the public assets (aka the Flamegraph stuff) wasn't bundled with the gem, so it could not be found by the parent application :facepalm: 

Should be fixed in the latest release, if you want to give it a try.
