### ISSUE TITLE
Fix for apps that don't use sprockets

### ISSUE THREAD

**Issue by hschne** [hschne/rails-mini-profiler#55]
RMP doesn't work for apps without sprockets. Most likely those created with `rails new --no-sprockets?`.

See #8. See [here](https://github.com/hschne/rails-mini-profiler/blob/66fe82cd2dca6ff500d794ef80e5c2b41910c5d3/lib/rails_mini_profiler/engine.rb#L14).

```ruby
# engine.rb
initializer 'rails_mini_profiler.assets.precompile', group: :all do |app|
    app.config.assets.precompile += %w[
      rails_mini_profiler.js
      rails_mini_profiler/application.css
      vendor/assets/images
    ]
end
```

**Comment by hschne** [comment]
@leastbad This _should_ make RMP work for apps that eliminated sprockets _with extreme prejudice_ :skull: 

If you want to give it a try from master you can do so right away: 

```
gem 'rails_mini_profiler', git: 'https://github.com/hschne/rails-mini-profiler'
```

:crossed_fingers:

**Comment by leastbad** [comment]
It worked, Hans! Great job. Such a cool project, I'm already excited to put it to work.

I have a bunch of ideas and general feedback for you.

Big picture: I urge you to strongly consider moving from Postgres to Redis as a datastore. There might be a reason for using Postgres I don't currently perceive, but having to add a migration increases friction.

Instead, consider using the [Kredis](https://github.com/rails/kredis/) library, and possibly [AllFutures](https://allfutures.leastbad.com/) to create a model-like persistence (more on this in a moment). One nice side-effect of using Redis is that you can rely on the key eviction policy to remove the oldest data, no need for a cleanup task.

It would be really great to be able to have the data appear on a div that is on the current page, instead of the current behaviour which does a full navigation to a separate page. One of the easiest ways for this to happen is to use [CableReady](https://cableready.stimulusreflex.com/) to send the data via ActionCable.

It would also be really great to be able to see the timing on Reflexes, as well as Controllers that get called as part of Page Morphs. Seeing profiling data on Reflexes would be a radical ergonomics improvement for the thousands of SR developers out there.

I will likely attempt to implement these ideas sooner or later on my own if you aren't excited about them, but my backlog is punishing so it's not clear when it could happen. 🤷‍♂️ 

Anyhow, I will be telling folks about this library for sure! Already posted on the [StimulusReflex Discord](https://discord.gg/stimulus-reflex).

**Comment by hschne** [comment]
Thanks for the invite :blush: 

> It would also be really great to be able to see the timing on Reflexes, as well as Controllers that get called as part of Page Morphs. Seeing profiling data on Reflexes would be a radical ergonomics improvement for the thousands of SR developers out there.

Yes. Julian already pitched that idea, definitely open to that. There's already something [on the roadmap](https://github.com/hschne/rails-mini-profiler/projects/2#card-65995680), but it's a far way off :wink: 

Regarding further dependencies (e.g. Redis, CableReady, Kredis...): I want to keeo RMP simple for now. I want any Rails app to be able to use it with minimal effort, and that for now means relying on the the DB the user already has. Running a migration adds friction, I agree, but forcing people to use additional services adds more I believe :zany_face:  

I want to add support for the features you suggested (alternative storage engines, better UI) in the future, but probably in the  form of extensive configuration options and plugins :)

I created an issue for your suggestions, feel free to create more. I'd be super happy if you were to contribute some code :heart:

**Comment by leastbad** [comment]
For sure! With all of the usual caveats about time. 💙
